### PR TITLE
WIP: Show broken pagetemplates

### PR DESCRIPTION
**Pull request by viktordick**
The goal of this PR is to have more information if a PageTemplate could not be parsed. If such an error occurs, it prints out information like the line number and the current tag.

Unfortunately, the tests are broken by this.

### CODE REVIEW

**Comment by viktordick** [comment]
Notes to myself about this PR:

- The tests in `test_main.py` fail because sometimes the `PTParseError` is printed twice (the background is that sometimes I do not know enough deep down in the code to have all the information, so I print it out there and raise the error and print it out again. It would be better to only print them at the top)
- Also, unless `--only-check-syntax` is given, the error is raised. The test does not expect that.
- Even though I get more information about the first occuring error within a parsed file, the program then breaks. It would be better to still be able to collect errors.
- When a file is parsed, the errors should be accumulated and given as a single Error to the main handler. Maybe the handler should then switch to dry-run mode?

**Comment by viktordick** [comment]
@icemac, I would like to get your opinion on some ideas about this PR and the direction I think this should go before I start fixing the tests with this.

In essence, I think instead of `--only-check-syntax`, it would be more helpful to have an argument like `--collect-errors`.

Without `--collect-errors`, the program would quit on the first encountered parsing error (maybe still showing all errors of the current file and not only the first one, but in any case not continuing to handle more files). With `--collect-errors`, it would continue to try to parse all given files, printing all errors and only exiting at the end with a non-zeo return code.

In contrast to `--only-check-errors`, `--collect-errors` will continue to rewrite the files if no error is encountered.

In each case, encountering an error will cause *no* file to be rewritten at the end and will return with a non-zero return code.

Additionally, it might be possible to implement a `--dry-run` option that keeps the files' contents even if no error is encountered. But I don't think this is too necessary, this can be done by backups and version control systems.

The idea would be to run the rewriter on a recording of a Zope2 installation, transforming everything to Python 3. If there are errors, it would be helpful to get a full list of things that should be fixed already in the Zope2 installation. After getting this list, the process should stop.

It might also be helpful to print the standard message of `Processing ...` on logging level `INFO` to `stdout`, while the parsing errors go to logging level `ERROR` on stderr. But it seems that this is not worth the hassle, it seems this is no so easy with `logging` and I can easily work around this by filtering the output.

One thing I would like to implement, however, is the possibility to obtain filenames from `stdin`. In the typical installations that I deal with, the argument list otherwise becomes to long to run everything at once and if I split the command using xargs, I have no longer the possibility to keep all files untouched if an error is encountered in a file later in the list.

As a side note: there was a code block in `PythonExpressionFilter` where, if a `PTParseError` is encountered, the `rewritten_value` falls back to the unchanged `value`. I think instead of keeping the value, this should also be handled as a parsing error.

**Comment by icemac** [comment]
@viktordick I like your ideas:

* I see no need for a `--dry-run` especially if there is a `--collect-errors`.
* Reading filenames from `stdin` is a nice idea but should be done in a separate PR.
* Regarding your site note: I think we added this behavior because of some jQuery documentation files which could not be excluded otherwise. So this could go away with the `stdin` filename support.

**Comment by jugmac00** [comment]
Thank you @viktordick for this PR!

I can confirm that instead of getting a misleading **AttributeError** now the exact line of the error is shown - that is a great improvement!

**Comment by viktordick** [comment]
@jugmac00 since you are waiting for this, an update: September was crazy and I could not continue with this. I am planning to finish it in October, hopefully in the first half of it.

**Comment by jugmac00** [comment]
@viktordick No need to hurry! I am lacking time myself. I just wanted to let everybody know that I won't start before this pr got merged, as otherwise I had to touch the documentation twice and think about what to write now and what later. Life is complicated enough as it is :-)

**Comment by viktordick** [comment]
@icemac The tests are fixed and the coverage is actually also at 100% again, but coveralls seems to be stuck. Maybe it's the same problem as in https://github.com/lemurheavy/coveralls-public/issues/905? Could you trigger a re-check?

**Comment by jugmac00** [comment]
@icemac Could you please "unstuck" coveralls via Viktor's link?

Can this pr be merged?

**Comment by icemac** [comment]
@viktordick Thank you, do you need a new release of this package?

**Comment by viktordick** [comment]
@icemac Thanks! I guess the package is ready for a released 0.1 at least.

**Comment by icemac** [comment]
I just released https://pypi.org/project/gocept.template-rewrite/1.0/

**Pull request merged**
